In [1]:
import os # Load library os dari Python

print(os.listdir('.')) # List semua file di directory sekarang (.)

print(os.listdir('./sample_data')) # List file di directory sample_data

['.config', 'sample_data']
['anscombe.json', 'README.md', 'california_housing_train.csv', 'mnist_train_small.csv', 'mnist_test.csv', 'california_housing_test.csv']

In [2]:
import pandas as pd
df = pd.read_csv (r'./sample_data/california_housing_train.csv') 

# print (df)

mean_housing_median_age = df['housing_median_age'].mean()
standar_deviation_housing_median_age = df['housing_median_age'].std()
maximum_housing_median_age = df['housing_median_age'].max()
minimum_housing_median_age = df['housing_median_age'].min()
quantile_1_housing_median_age = df.housing_median_age.quantile(0.25)
quantile_2_housing_median_age = df.housing_median_age.quantile(0.5)
quantile_3_housing_median_age = df.housing_median_age.quantile(0.75)

mean_total_rooms = df['total_rooms'].mean()
standar_deviation_total_rooms = df['total_rooms'].std()
maximum_total_rooms = df['total_rooms'].max()
minimum_total_rooms = df['total_rooms'].min()
quantile_1_total_rooms = df.total_rooms.quantile(0.25)
quantile_2_total_rooms = df.total_rooms.quantile(0.5)
quantile_3_total_rooms = df.total_rooms.quantile(0.75)

mean_total_bedrooms = df['total_bedrooms'].mean()
standar_deviation_total_bedrooms = df['total_bedrooms'].std()
maximum_total_bedrooms = df['total_bedrooms'].max()
minimum_total_bedrooms = df['total_bedrooms'].min()
quantile_1_total_bedrooms = df.total_bedrooms.quantile(0.25)
quantile_2_total_bedrooms = df.total_bedrooms.quantile(0.5)
quantile_3_total_bedrooms = df.total_bedrooms.quantile(0.75)

mean_population = df['population'].mean()
standar_deviation_population = df['population'].std()
maximum_population = df['population'].max()
minimum_population = df['population'].min()
quantile_1_population = df.population.quantile(0.25)
quantile_2_population = df.population.quantile(0.5)
quantile_3_population = df.population.quantile(0.75)

mean_households = df['households'].mean()
standar_deviation_households = df['households'].std()
maximum_households = df['households'].max()
minimum_households = df['households'].min()
quantile_1_households = df.households.quantile(0.25)
quantile_2_households = df.households.quantile(0.5)
quantile_3_households = df.households.quantile(0.75)

mean_median_income = df['median_income'].mean()
standar_deviation_median_income = df['median_income'].std()
maximum_median_income = df['median_income'].max()
minimum_median_income = df['median_income'].min()
quantile_1_median_income = df.median_income.quantile(0.25)
quantile_2_median_income = df.median_income.quantile(0.5)
quantile_3_median_income = df.median_income.quantile(0.75)

mean_median_house_value = df['median_house_value'].mean()
standar_deviation_median_house_value = df['median_house_value'].std()
maximum_median_house_value = df['median_house_value'].max()
minimum_median_house_value = df['median_house_value'].min()
quantile_1_median_house_value = df.median_house_value.quantile(0.25)
quantile_2_median_house_value = df.median_house_value.quantile(0.5)
quantile_3_median_house_value = df.median_house_value.quantile(0.75)

print("Housing Median Age:")

print ('\n    Mean              : ' + str(mean_housing_median_age),
       '\n    Standar Devation  : ' + str(standar_deviation_housing_median_age),
       '\n    Maksimum          : ' + str(maximum_housing_median_age),
       '\n    Minimum           : ' + str(minimum_housing_median_age),
       '\n    Kuartil 1         : ' + str(quantile_1_housing_median_age),
       '\n    Kuartil 2         : ' + str(quantile_2_housing_median_age),
       '\n    Kuartil 3         : ' + str(quantile_3_housing_median_age))
print()

print("Total Rooms:")

print ('\n    Mean              : ' + str(mean_total_rooms),
       '\n    Standar Devation  : ' + str(standar_deviation_total_rooms),
       '\n    Maksimum          : ' + str(maximum_total_rooms),
       '\n    Minimum           : ' + str(minimum_total_rooms),
       '\n    Kuartil 1         : ' + str(quantile_1_total_rooms),
       '\n    Kuartil 2         : ' + str(quantile_2_total_rooms),
       '\n    Kuartil 3         : ' + str(quantile_3_total_rooms))
print()

print("Total Bedrooms:")

print ('\n    Mean              : ' + str(mean_total_bedrooms),
       '\n    Standar Devation  : ' + str(standar_deviation_total_bedrooms),
       '\n    Maksimum          : ' + str(maximum_total_bedrooms),
       '\n    Minimum           : ' + str(minimum_total_bedrooms),
       '\n    Kuartil 1         : ' + str(quantile_1_total_bedrooms),
       '\n    Kuartil 2         : ' + str(quantile_2_total_bedrooms),
       '\n    Kuartil 3         : ' + str(quantile_3_total_bedrooms))
print()

print("Population:")

print ('\n    Mean              : ' + str(mean_population),
       '\n    Standar Devation  : ' + str(standar_deviation_population),
       '\n    Maksimum          : ' + str(maximum_population),
       '\n    Minimum           : ' + str(minimum_population),
       '\n    Kuartil 1         : ' + str(quantile_1_population),
       '\n    Kuartil 2         : ' + str(quantile_2_population),
       '\n    Kuartil 3         : ' + str(quantile_3_population))
print()

print("Households:")

print ('\n    Mean              : ' + str(mean_households),
       '\n    Standar Devation  : ' + str(standar_deviation_households),
       '\n    Maksimum          : ' + str(maximum_households),
       '\n    Minimum           : ' + str(minimum_households),
       '\n    Kuartil 1         : ' + str(quantile_1_households),
       '\n    Kuartil 2         : ' + str(quantile_2_households),
       '\n    Kuartil 3         : ' + str(quantile_3_households))
print()

print("Median income:")

print ('\n    Mean              : ' + str(mean_median_income),
       '\n    Standar Devation  : ' + str(standar_deviation_median_income),
       '\n    Maksimum          : ' + str(maximum_median_income),
       '\n    Minimum           : ' + str(minimum_median_income),
       '\n    Kuartil 1         : ' + str(quantile_1_median_income),
       '\n    Kuartil 2         : ' + str(quantile_2_median_income),
       '\n    Kuartil 3         : ' + str(quantile_3_median_income))
print()

print("Median House Value:")

print ('\n    Mean              : ' + str(mean_median_house_value),
       '\n    Standar Devation  : ' + str(standar_deviation_median_house_value),
       '\n    Maksimum          : ' + str(maximum_median_house_value),
       '\n    Minimum           : ' + str(minimum_median_house_value),
       '\n    Kuartil 1         : ' + str(quantile_1_median_house_value),
       '\n    Kuartil 2         : ' + str(quantile_2_median_house_value),
       '\n    Kuartil 3         : ' + str(quantile_3_median_house_value))
print()

Housing Median Age:

    Mean              : 28.58935294117647
    Standar Devation  : 12.586936981660335
    Maksimum          : 52.0
    Minimum           : 1.0
    Kuartil 1         : 18.0
    Kuartil 2         : 29.0
    Kuartil 3         : 37.0

Total Rooms:

    Mean              : 2643.664411764706
    Standar Devation  : 2179.947071452768
    Maksimum          : 37937.0
    Minimum           : 2.0
    Kuartil 1         : 1462.0
    Kuartil 2         : 2127.0
    Kuartil 3         : 3151.25

Total Bedrooms:

    Mean              : 539.4108235294118
    Standar Devation  : 421.49945157986514
    Maksimum          : 6445.0
    Minimum           : 1.0
    Kuartil 1         : 297.0
    Kuartil 2         : 434.0
    Kuartil 3         : 648.25

Population:

    Mean              : 1429.5739411764705
    Standar Devation  : 1147.852959159525
    Maksimum          : 35682.0
    Minimum           : 3.0
    Kuartil 1         : 790.0
    Kuartil 2         : 1167.0
    Kuartil 3         : 1721.0

Households:

    Mean              : 501.2219411764706
    Standar Devation  : 384.52084085590013
    Maksimum          : 6082.0
    Minimum           : 1.0
    Kuartil 1         : 282.0
    Kuartil 2         : 409.0
    Kuartil 3         : 605.25

Median income:

    Mean              : 3.883578100000021
    Standar Devation  : 1.908156518379093
    Maksimum          : 15.0001
    Minimum           : 0.4999
    Kuartil 1         : 2.566375
    Kuartil 2         : 3.5446
    Kuartil 3         : 4.767

Median House Value:

    Mean              : 207300.91235294117
    Standar Devation  : 115983.76438720913
    Maksimum          : 500001.0
    Minimum           : 14999.0
    Kuartil 1         : 119400.0
    Kuartil 2         : 180400.0
    Kuartil 3         : 265000.0

In [ ]:
dk = df.describe()
dk = dk.drop(columns=['longitude','latitude'],axis=1,inplace = False)
dk

       housing_median_age   total_rooms  ...  median_income  median_house_value
count        17000.000000  17000.000000  ...   17000.000000        17000.000000
mean            28.589353   2643.664412  ...       3.883578       207300.912353
std             12.586937   2179.947071  ...       1.908157       115983.764387
min              1.000000      2.000000  ...       0.499900        14999.000000
25%             18.000000   1462.000000  ...       2.566375       119400.000000
50%             29.000000   2127.000000  ...       3.544600       180400.000000
75%             37.000000   3151.250000  ...       4.767000       265000.000000
max             52.000000  37937.000000  ...      15.000100       500001.000000

[8 rows x 7 columns]

In [11]:
import numpy
from statistics import mean


directory = os.path.join('sample_data', 'california_housing_train.csv') # Output: sample_data/california_housing_train.csv

# print(directory)

# if os.path.isfile(directory):
#   print("File ditemukan")

text_file = open(directory, "r") # "r" = moud read

# print(text_file.read())

lines = text_file.readlines()

# print(lines)

# print("Jumlah data (original) ", len(lines))

# for line in lines[:3]: # Print 3 baris pertama
#   print(line)

  # line = line.strip() #fungsi nya menghapus spasi/enter di depan suatu text

  # split_columns = line.split(",")

  # print(split_columns)

#parsed_values = []
housing, room, bedroom, population, household, mincome, mhouse = [], [], [], [], [], [], []

for index, line in enumerate(lines):
  split_columns = line.split(",")

  if index == 0: #menskip judul
    continue
  housing.append(float(split_columns[2]))
  room.append(float(split_columns[3]))
  bedroom.append(float(split_columns[4]))
  population.append(float(split_columns[5]))
  household.append(float(split_columns[6]))
  mincome.append(float(split_columns[7]))
  mhouse.append(float(split_columns[8]))

# parsed_values.append([float(split_columns[0]), float(split_columns[1]), float(split_columns[2]), float(split_columns[3]), float(split_columns[4]), float(split_columns[5]), float(split_columns[6]), float(split_columns[7]), float(split_columns[8])])

# print("Jumlah data (parsed) ", len(parsed_values))

# print(parsed_values)

def fungsi(attribute):
  print("Nilai Mean adalah                  :", mean(attribute))
  print("Standard Deviasi adalah:           :", numpy.std(attribute))
  print("Nilai Minimum adalah               :", min(attribute))
  print("Nilai Maximum adalah               :", max(attribute))
  print("Nilai Q1 (Kuartil pertama) adalah  :", numpy.percentile(attribute, 25))
  print("Nilai Q2 (Kuartil kedua) adalah    :", numpy.percentile(attribute, 50))
  print("Nilai Q3 (Kuartil ketiga) adalah   :", numpy.percentile(attribute, 75))
  for n in attribute:
    if n == None:
      print("Terdapat nilai kosong/bernilai 0")
    else:
      print("Tidak terdapat nilai kosong/bernilai 0")
    break
  print("\n")
  return 

print("1. Housing Median Age")
print("=====================")
fungsi(housing)
print("2. Total Rooms")
print("==============")
fungsi(room)
print("3. Total Bedrooms")
print("=================")
fungsi(bedroom)
print("4. Population")
print("=============")
fungsi(population)
print("5. Households")
print("=============")
fungsi(household)
print("6. Median Income")
print("================")
fungsi(mincome)
print("7. Median House Value")
print("=====================")
fungsi(mhouse)

1. Housing Median Age
=====================
Nilai Mean adalah                  : 28.58935294117647
Standard Deviasi adalah:           : 12.58656677218719
Nilai Minimum adalah               : 1.0
Nilai Maximum adalah               : 52.0
Nilai Q1 (Kuartil pertama) adalah  : 18.0
Nilai Q2 (Kuartil kedua) adalah    : 29.0
Nilai Q3 (Kuartil ketiga) adalah   : 37.0
Tidak terdapat nilai kosong/bernilai 0


2. Total Rooms
==============
Nilai Mean adalah                  : 2643.664411764706
Standard Deviasi adalah:           : 2179.8829544195187
Nilai Minimum adalah               : 2.0
Nilai Maximum adalah               : 37937.0
Nilai Q1 (Kuartil pertama) adalah  : 1462.0
Nilai Q2 (Kuartil kedua) adalah    : 2127.0
Nilai Q3 (Kuartil ketiga) adalah   : 3151.25
Tidak terdapat nilai kosong/bernilai 0


3. Total Bedrooms
=================
Nilai Mean adalah                  : 539.4108235294118
Standard Deviasi adalah:           : 421.4870543548563
Nilai Minimum adalah               : 1.0
Nilai Maximum adalah               : 6445.0
Nilai Q1 (Kuartil pertama) adalah  : 297.0
Nilai Q2 (Kuartil kedua) adalah    : 434.0
Nilai Q3 (Kuartil ketiga) adalah   : 648.25
Tidak terdapat nilai kosong/bernilai 0


4. Population
=============
Nilai Mean adalah                  : 1429.5739411764705
Standard Deviasi adalah:           : 1147.819198281884
Nilai Minimum adalah               : 3.0
Nilai Maximum adalah               : 35682.0
Nilai Q1 (Kuartil pertama) adalah  : 790.0
Nilai Q2 (Kuartil kedua) adalah    : 1167.0
Nilai Q3 (Kuartil ketiga) adalah   : 1721.0
Tidak terdapat nilai kosong/bernilai 0


5. Households
=============
Nilai Mean adalah                  : 501.2219411764706
Standard Deviasi adalah:           : 384.50953125308496
Nilai Minimum adalah               : 1.0
Nilai Maximum adalah               : 6082.0
Nilai Q1 (Kuartil pertama) adalah  : 282.0
Nilai Q2 (Kuartil kedua) adalah    : 409.0
Nilai Q3 (Kuartil ketiga) adalah   : 605.25
Tidak terdapat nilai kosong/bernilai 0


6. Median Income
================
Nilai Mean adalah                  : 3.8835781
Standard Deviasi adalah:           : 1.9081003953032116
Nilai Minimum adalah               : 0.4999
Nilai Maximum adalah               : 15.0001
Nilai Q1 (Kuartil pertama) adalah  : 2.566375
Nilai Q2 (Kuartil kedua) adalah    : 3.5446
Nilai Q3 (Kuartil ketiga) adalah   : 4.767
Tidak terdapat nilai kosong/bernilai 0


7. Median House Value
=====================
Nilai Mean adalah                  : 207300.91235294117
Standard Deviasi adalah:           : 115980.35304985354
Nilai Minimum adalah               : 14999.0
Nilai Maximum adalah               : 500001.0
Nilai Q1 (Kuartil pertama) adalah  : 119400.0
Nilai Q2 (Kuartil kedua) adalah    : 180400.0
Nilai Q3 (Kuartil ketiga) adalah   : 265000.0
Tidak terdapat nilai kosong/bernilai 0